### ISSUE TITLE
Handler should bind to the same address component as the Server

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#10]
IIRC right now it chooses `0.0.0.0:port`, but if the server chose `127.0.0.1:port` then the handler should too.

[std::net::UdpSocket::local_addr](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.local_addr) may be useful here. This could be done in `Server::serve`.

**Comment by itmecho** [comment]
I'd like to implement this one if that's cool?

**Comment by connorkuehl** [comment]
Sure :slightly_smiling_face:
