### ISSUE TITLE
connection::Connection should transmit the Error packet

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#11]
Right now it just uses the Error packet to create an `io::Error`. It'd be best to transmit the courtesy Error packet before returning the `io::Error`. 

Do this for `put` and `get`.

**Comment by PurpleMyst** [comment]
Hi, I'm interested in working on this. To clarify, do you want to send an Error packet on `io::{Read, Write}` errors?

**Comment by connorkuehl** [comment]
Hi @PurpleMyst! Thank you! 🙂 

> To clarify, do you want to send an Error packet on io::{Read, Write} errors in the given reader/writer?

No, we want to send the packet over the UDP socket, not the Read or Write objects. Depending on whether we're talking about `get` or `put`:

* The `Read` object is the data we are sending over the socket. So we read from the `Read` object, create a packet, and send it.
* The `Write` object is the place where we store the data that we receive. So we read from the socket, take the data out of the packet, and use the `Write `object to save it.

Right now, `get` will [attempt to parse an Error packet](https://github.com/connorkuehl/tftp/blob/main/src/connection.rs#L28) if it failed to parse a Data packet it's expecting. If parsing the Error packet fails, then it returns early with an error.

Likewise, `put` will [attempt to parse an Error packet](https://github.com/connorkuehl/tftp/blob/main/src/connection.rs#L63) if it doesn't parse the Ack packet it's expecting. If parsing the Error packet fails, then it returns early with an error.

For this issue, I don't want it to return early without sending an Error packet to its peer. That is:

IF we fail to parse the packet we're expecting AND we fail to parse an Error packet, that means we've received a packet that doesn't make sense and the connection should not continue. In this case, we will create an Error packet, send it to the peer, and then return an error.

Does that help any?

**Comment by PurpleMyst** [comment]
Understood. So my PR is totally unrelated to this issue, but does fix another issue. Should I tack on this change to my already-existing PR or create another one?

**Comment by connorkuehl** [comment]
A separate PR would be best. Thanks! 🙂

**Comment by PurpleMyst** [comment]
Alright, I've unlinked #41 from this issue and created a new, linked, pull request numbered #43 
The two are independent from eachother, so you can pick and choose when and if to merge them :)
