### ISSUE TITLE
Expand CI to run on MacOS

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#20]
I haven't checked with Travis to see if this is a part of its free offering, but it would be cool. Off the top of my head there's nothing Linux-specific in this repo.

**Comment by dynomite567** [comment]
I can take a look into this. I have had experience in Travis before, and I am very certain MacOS is part of the free tier.

**Comment by connorkuehl** [comment]
Thanks, @dynomite567! Please don't hesitate to let me know if I can be of any help.

**Comment by dynomite567** [comment]
There was not much to change, since macOS is mainly UNIX, and travis makes it easy for rust to be setup. Hopefully this contribution helps! If there's anything you want me to change or add, let me know.

**Comment by connorkuehl** [comment]
Closed by #23
