### ISSUE TITLE
Server should send an error packet if the client wants to PUT a file that already exists

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#24]
This could probably be accomplished in `server::Handler::put` by replacing the `create` and `truncate` options with [`OptionOptions::create_new`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.create_new).

**Comment by f3rn0s** [comment]
Opened a PR to address this. See #25

**Comment by connorkuehl** [comment]
Closed by #25 
Merged in as 3d9b6c8fdb057c6e97b1de2733119f32970c743b
