### ISSUE TITLE
Add a unit test for when the client initiates a connect with a packet that is *not* a read or write request

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#29]
If `Server::serve` receives a packet that is _not_ a read/write request, it will create an Error packet and send it to the client.

We should have a test to confirm this behavior.

**Comment by noblehelm** [comment]
I'd like to give this one a shot. Thanks in advance.

**Comment by connorkuehl** [comment]
I appreciate that a lot! Thanks, @noblehelm. Please don't hesitate to let me know if I can help out at all.
