### ISSUE TITLE
impl Clone for client::Builder<ConnectTo>

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#33]
TFTP doesn't reuse any connections and so the `struct Client` API is designed to reflect that -- meaning that a Client can't be cloned/copied to attempt to use it again.

However, if one wants to make several requests to a Server, it would be very handy if `Builder<ConnectTo>` implemented the `Clone` trait so they can clone this as many times as they want and then construct their own unique clients from that.

This isn't as simple as `#[derive(Clone)]` on the `Builder<ConnectTo>` because I specifically want each `Builder<ConnectTo>` to have its own _unique_ socket. TFTP considers each `address:port` to represent a unique _Transfer ID_ and therefore if we reused a socket that would mean the transfer ID previously used is no longer unique.

**Comment by ChiefMilesEdgeworth** [comment]
Could I try my hand at this? Looks like it shouldn't be _too_ hard, but I may need guidance on something as I go (I haven't had to work with sockets and stuff like that a whole lot before).

**Comment by ChiefMilesEdgeworth** [comment]
Working through it, it looks like both `new` and `connect_to` and `Builder<New>` can fail, and given that we would need to bind to a different port each time `clone` should be able to fail too. Should we be trying to implement `TryClone` or some similar trait, or should we be unwrapping and expecting the connection to work?

**Comment by connorkuehl** [comment]
> Could I try my hand at this? Looks like it shouldn't be _too_ hard, but I may need guidance on something as I go (I haven't had to work with sockets and stuff like that a whole lot before).

Hey @ChiefMilesEdgeworth! That'd be awesome, thank you.

> Working through it, it looks like both new and connect_to and Builder<New> can fail, and given that we would need to bind to a different port each time clone should be able to fail too. Should we be trying to implement TryClone or some similar trait, or should we be unwrapping and expecting the connection to work?

I don't think TryClone is a trait provided by the std lib. I think the right way forward here would be to add a method called `try_clone` to `Builder<ConnectTo>` to avoid having to unwrap.

Please don't hesitate to ping me if I can be of any assistance 🙂
