### ISSUE TITLE
Create a constant for the lower bound of the port range

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#34]
Right now, the `Server::random_port` and `client::Builder::<New>::new` methods have different lower bounds for port selection.

Expose a constant (maybe in the `connection` module) and update both of those places to use that constant instead.

**Comment by soumyarup-paul** [comment]
Hi, can you please assign this ticket to me?

**Comment by connorkuehl** [comment]
Thank you very much, @soumyarup-paul! I'll take a look at your PR. 🙂
