### ISSUE TITLE
Replace the assert statement in connection::Connection::put with an error packet and terminate the transmission

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#35]
A misbehaving peer could send us an ack with the wrong block number; however, panicking via an assert is not a helpful way to deal with this.

We don't need to go out of our way to try to get the connection back on track. Create a courtesy Error packet, send it to the peer, and then return early from this method with an err.

**Comment by 1c3t3a** [comment]
Hey Connor, I would like to work on this!

**Comment by connorkuehl** [comment]
Awesome! Thanks 🙂
