### ISSUE TITLE
Add documentation for using Wireshark to capture TFTP packets

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#42]
Commit this as **Documentation/wireshark.md**.

Wireshark is a helpful tool for debugging network protocols.

For example, I can capture the packets sent during the unit tests by opening Wireshark, selecting the loopback interface, and then running `cargo test`. Then stop capture.

**Comment by snasphysicist** [comment]
Hi @connorkuehl I have also worked with Wireshark a bit and I would be happy to write this documentation.

**Comment by connorkuehl** [comment]
Thank you very much, @snasphysicist! 🙂

**Comment by connorkuehl** [comment]
Closed by #58
