### ISSUE TITLE
Add a threadpool server example

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#5]
The way `server::Server` is implemented, it should be fairly trivial to move `server::Handler` across thread boundaries. The `server::Server` instance could listen on the initial thread and then submit `server::Handler` jobs to the threadpool.

Put it under the **examples/** folder.

**Comment by nidble** [comment]
Can I work on this? Thanks!

**Comment by connorkuehl** [comment]
That'd be great! Thank you, @nidble. Don't hesitate to let me know if I can help out any.
