### ISSUE TITLE
Add final packet dallying

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#56]
When a `get` connection sends its final ACK, it should wait to see if the server sends the last data packet again. This suggests that the server did not receive the final ACK for the final data packet.

**Comment by 1c3t3a** [comment]
Hey Connor, I'd like to tackle this!

**Comment by 1c3t3a** [comment]
What would you suggest is the right time to wait if the server still sends a packet? Maybe I could wait till #47 get merged and use the retransmission timeout specified there.

**Comment by connorkuehl** [comment]
Sweet, thanks!

> What would you suggest is the right time to wait if the server still sends a packet?

Let's keep it low for now... maybe 3 seconds?

> Maybe I could wait till #47 get merged and use the retransmission timeout specified there.

Up to you if you want to wait!

**Comment by 1c3t3a** [comment]
Alright, I'm gonna do this now!
