### ISSUE TITLE
Add CI to repo

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#9]
At the very least, the repo should run `cargo test`. Probably through Travis CI or GitHub actions?

If other issues like #2 #3 are completed prior to this one, they should be included in the CI as well or additional GitHub issues should be generated to track that work.

**Comment by itmecho** [comment]
Hi @connorkuehl , I can give this a shot! What build targets and rust versions did you have in mind?

**Comment by connorkuehl** [comment]
Thanks @itmecho! I don't plan to enforce a minimum Rust version at this time. I think as long as it can build and run tests etc on Linux we have a good starting point. I see you opened a pull request earlier and I'll be able to take a look at that soon.
